=== francepiafrancepia-hue/ideal-octo-fishstick/schemas/institutional-master.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:inst="http://institution.example.org/master"
           targetNamespace="http://institution.example.org/master"
           elementFormDefault="qualified">
    
    <xs:annotation>
        <xs:documentation>
            Institutional Master Record Schema
            This schema defines the master record format for institutional data.
            All source formats should be transformed to this master format.
        </xs:documentation>
    </xs:annotation>
    
    <!-- Root element -->
    <xs:element name="InstitutionalRecord" type="inst:InstitutionalRecordType"/>
    
    <!-- Main record type -->
    <xs:complexType name="InstitutionalRecordType">
        <xs:sequence>
            <xs:element name="Metadata" type="inst:MetadataType"/>
            <xs:element name="Entity" type="inst:EntityType"/>
            <xs:element name="Traceability" type="inst:TraceabilityType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="version" type="xs:string" use="required"/>
        <xs:attribute name="recordId" type="xs:string" use="required"/>
    </xs:complexType>
    
    <!-- Metadata type -->
    <xs:complexType name="MetadataType">
        <xs:sequence>
            <xs:element name="CreatedDate" type="xs:dateTime"/>
            <xs:element name="ModifiedDate" type="xs:dateTime"/>
            <xs:element name="Source" type="xs:string"/>
            <xs:element name="TransformationRef" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Entity type -->
    <xs:complexType name="EntityType">
        <xs:sequence>
            <xs:element name="Identifier" type="inst:IdentifierType"/>
            <xs:element name="Name" type="inst:NameType"/>
            <xs:element name="Description" type="xs:string" minOccurs="0"/>
            <xs:element name="Attributes" type="inst:AttributesType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Identifier type -->
    <xs:complexType name="IdentifierType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="xs:string" use="required"/>
                <xs:attribute name="sourceId" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>Original identifier from source system for traceability</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <!-- Name type -->
    <xs:complexType name="NameType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="sourceName" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>Original name from source system for traceability</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <!-- Attributes type -->
    <xs:complexType name="AttributesType">
        <xs:sequence>
            <xs:element name="Attribute" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="name" type="xs:string" use="required"/>
                            <xs:attribute name="sourceField" type="xs:string" use="optional">
                                <xs:annotation>
                                    <xs:documentation>Source field name for bidirectional traceability</xs:documentation>
                                </xs:annotation>
                            </xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Traceability type for bidirectional mapping -->
    <xs:complexType name="TraceabilityType">
        <xs:sequence>
            <xs:element name="SourceMapping" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="institutionalElement" type="xs:string" use="required"/>
                    <xs:attribute name="sourceElement" type="xs:string" use="required"/>
                    <xs:attribute name="transformationRule" type="xs:string" use="optional"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== francepiafrancepia-hue/ideal-octo-fishstick/examples/institutional-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<inst:InstitutionalRecord xmlns:inst="http://institution.example.org/master"
                          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                          xsi:schemaLocation="http://institution.example.org/master ../schemas/institutional-master.xsd"
                          version="1.0"
                          recordId="SRC-12345">
    <inst:Metadata>
        <inst:CreatedDate>2026-01-14T10:00:00Z</inst:CreatedDate>
        <inst:ModifiedDate>2026-01-14T12:30:00Z</inst:ModifiedDate>
        <inst:Source>Legacy System v2.1</inst:Source>
        <inst:TransformationRef>source-to-institutional.xsl</inst:TransformationRef>
    </inst:Metadata>
    <inst:Entity>
        <inst:Identifier type="institutional" sourceId="ITEM-ABC-789">SRC-12345</inst:Identifier>
        <inst:Name sourceName="Sample Document Title">Sample Document Title</inst:Name>
        <inst:Description>This is a detailed description of the sample document from the legacy system.</inst:Description>
        <inst:Attributes>
            <inst:Attribute name="category" sourceField="category">Research</inst:Attribute>
            <inst:Attribute name="status" sourceField="status">Active</inst:Attribute>
            <inst:Attribute name="priority" sourceField="priority">High</inst:Attribute>
        </inst:Attributes>
    </inst:Entity>
    <inst:Traceability>
        <inst:SourceMapping institutionalElement="InstitutionalRecord/@recordId" 
                           sourceElement="SourceRecord/@id" 
                           transformationRule="direct-copy"/>
        <inst:SourceMapping institutionalElement="Metadata/CreatedDate" 
                           sourceElement="RecordInfo/Created" 
                           transformationRule="direct-copy"/>
        <inst:SourceMapping institutionalElement="Metadata/ModifiedDate" 
                           sourceElement="RecordInfo/Updated" 
                           transformationRule="direct-copy"/>
        <inst:SourceMapping institutionalElement="Metadata/Source" 
                           sourceElement="RecordInfo/Origin" 
                           transformationRule="direct-copy"/>
        <inst:SourceMapping institutionalElement="Entity/Identifier" 
                           sourceElement="SourceRecord/@id" 
                           transformationRule="direct-copy"/>
        <inst:SourceMapping institutionalElement="Entity/Identifier/@sourceId" 
                           sourceElement="Item/ItemId" 
                           transformationRule="direct-copy"/>
        <inst:SourceMapping institutionalElement="Entity/Name" 
                           sourceElement="Item/Title" 
                           transformationRule="direct-copy"/>
        <inst:SourceMapping institutionalElement="Entity/Description" 
                           sourceElement="Item/Details" 
                           transformationRule="direct-copy"/>
        <inst:SourceMapping institutionalElement="Entity/Attributes/Attribute" 
                           sourceElement="Item/Properties/Property" 
                           transformationRule="key-to-name-mapping"/>
    </inst:Traceability>
</inst:InstitutionalRecord>
